trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - README.md
    - LICENSE

variables:
    # Base URI for ARM templates
    templateBaseUrl: '$(Build.Repository.Uri)/master/arm-templates/'

    # Debug switch for verbose output
    system.debug: true

pool:
  vmImage: 'windows-latest'

stages:

- stage: Validate
  displayName: Validate

  variables:
    # Resource group name to be used for template validation
    validationResourceGroupName: 'ghost-web-app-rg' # Could be any allowed name. The resource group will be automatically provisioned by template validation tasks

  jobs:
    - job: ValidateJob
      displayName: Validate ARM templates

      steps:
        - task: AzureResourceManagerTemplateDeployment@3
          displayName: Validate resource group template
          inputs:
            deploymentScope: 'Subscription'
            ConnectedServiceName: $(subscriptionName)
            subscriptionId: $(subscriptionId)
            location: $(location)
            templateLocation: 'Linked artifact'
            csmFile: '$(Build.Repository.LocalPath)/arm-templates/resource-group/azuredeploy.json'
            csmParametersFile: '$(Build.Repository.LocalPath)/arm-templates/resource-group/azuredeploy.parameters.json'
            deploymentMode: 'Validation'

        - task: AzureResourceManagerTemplateDeployment@3
          displayName: Validate Log Analytics workspace template
          inputs:
            deploymentScope: 'Resource Group'
            ConnectedServiceName: $(subscriptionName)
            subscriptionId: $(subscriptionId)
            action: 'Create Or Update Resource Group'
            resourceGroupName: $(validationResourceGroupName)
            location: $(location)
            templateLocation: 'Linked artifact'
            csmFile: '$(Build.Repository.LocalPath)/arm-templates/linked-templates/logAnalyticsWorkspace.json'
            csmParametersFile: '$(Build.Repository.LocalPath)/arm-templates/linked-templates/logAnalyticsWorkspace.parameters.json'
            deploymentMode: 'Validation'

        - task: AzureResourceManagerTemplateDeployment@3
          displayName: Validate Container Registry template
          inputs:
            deploymentScope: 'Resource Group'
            ConnectedServiceName: $(subscriptionName)
            subscriptionId: $(subscriptionId)
            action: 'Create Or Update Resource Group'
            resourceGroupName: $(validationResourceGroupName)
            location: $(location)
            templateLocation: 'Linked artifact'
            csmFile: '$(Build.Repository.LocalPath)/arm-templates/linked-templates/containerRegistry.json'
            csmParametersFile: '$(Build.Repository.LocalPath)/arm-templates/linked-templates/containerRegistry.parameters.json'
            deploymentMode: 'Validation'

        - task: AzureResourceManagerTemplateDeployment@3
          displayName: Validate Web App template
          inputs:
            deploymentScope: 'Resource Group'
            ConnectedServiceName: $(subscriptionName)
            subscriptionId: $(subscriptionId)
            action: 'Create Or Update Resource Group'
            resourceGroupName: $(validationResourceGroupName)
            location: $(location)
            templateLocation: 'Linked artifact'
            csmFile: '$(Build.Repository.LocalPath)/arm-templates/linked-templates/webApp.json'
            csmParametersFile: '$(Build.Repository.LocalPath)/arm-templates/linked-templates/webApp.parameters.json'
            deploymentMode: 'Validation'

        - task: AzureResourceManagerTemplateDeployment@3
          displayName: Validate main template
          inputs:
            deploymentScope: 'Resource Group'
            ConnectedServiceName: $(subscriptionName)
            subscriptionId: $(subscriptionId)
            action: 'Create Or Update Resource Group'
            resourceGroupName: $(validationResourceGroupName)
            location: $(location)
            templateLocation: 'Linked artifact'
            csmFile: '$(Build.Repository.LocalPath)/arm-templates/main-template/azuredeploy.json'
            csmParametersFile: '$(Build.Repository.LocalPath)/arm-templates/main-template/azuredeploy.parameters.json'
            deploymentMode: 'Validation'

        - task: AzureResourceManagerTemplateDeployment@3
          displayName: Remove validation resource group
          condition: always()
          inputs:
            deploymentScope: 'Resource Group'
            ConnectedServiceName: $(subscriptionName)
            subscriptionId: $(subscriptionId)
            resourceGroupName: $(validationResourceGroupName)
            action: 'DeleteRG'
            location: $(location)
            deploymentMode: 'Incremental'


- stage: DeployToTestEnvironment
  displayName: Deploy Azure resource
  dependsOn: Validate

  jobs:
  - deployment: DeploymentJob
    displayName: Deploy ARM templates
    environment: 'Test'
    strategy:
      runOnce:
        deploy:
          steps:
            - task: AzureResourceManagerTemplateDeployment@3
              displayName: Create a resource group
              inputs:
                deploymentScope: 'Subscription'
                ConnectedServiceName: $(subscriptionName)
                subscriptionId: $(subscriptionId)
                location: $(location)
                templateLocation: 'Linked artifact'
                csmFile: '$(Build.Repository.LocalPath)/arm-templates/resource-group/azuredeploy.json'
                csmParametersFile: '$(Build.Repository.LocalPath)/arm-templates/resource-group/azuredeploy.parameters.json'
                deploymentMode: 'Incremental'
                deploymentOutputs: 'armOutputs'

            - task: AzurePowerShell@4
              displayName: Get the resource group name
              inputs:
                azureSubscription: $(subscriptionName)
                scriptType: 'InlineScript'
                Inline: |
                  $var=ConvertFrom-Json '$(armOutputs)'
                  $value=$var.resourceGroupName.value
                  Write-Host "##vso[task.setvariable variable=resourceGroupName;]$value"
                azurePowerShellVersion: 'latestVersion'
                pwsh: true

            - task: AzureResourceManagerTemplateDeployment@3
              displayName: Deploy the resources to the resource group
              inputs:
                deploymentScope: 'Resource Group'
                ConnectedServiceName: $(subscriptionName)
                subscriptionId: $(subscriptionId)
                action: 'Create Or Update Resource Group'
                resourceGroupName: $(resourceGroupName)
                location: $(location)
                templateLocation: 'Linked artifact'
                csmFile: '$(Build.Repository.LocalPath)/arm-templates/main-template/azuredeploy.json'
                csmParametersFile: '$(Build.Repository.LocalPath)/arm-templates/main-template/azuredeploy.parameters.json'
                overrideParameters: '-linkedTemplateBaseUrl $(templateBaseUrl)/'
                deploymentMode: 'Incremental'
                deploymentOutputs: 'armOutputs'