trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - arm-templates/*
    - '**/README.md'
    - LICENSE

pool:
  vmImage: 'windows-latest'

stages:
  - stage: BuildContainer
    displayName: Build container

    jobs:
      - job: DockerJob
        displayName: Build and publish container image

        steps:

          - task: Docker@2
            displayName: Build and push image to container registry
            inputs:
              command: buildAndPush
              containerRegistry: GhostContainerRegistry
              dockerfile: '**/Dockerfile'
              tags: |
                $(Build.BuildId)
                latest

  # - stage: DeployContainer
  #   displayName: Deploy container

  #   jobs:
  #   - deployment: DeploymentJob
  #     displayName: Deploy Ghost container
  #     environment: 'Test'
  #     strategy:
  #       runOnce:
  #         deploy:
  #           steps:

  #           - task: AzureWebAppContainer@1
  #             displayName: Deploy container to Web App
  #             inputs:
  #               azureSubscription: $(subscriptionName)
  #               appName: ''
  #               containers: ''
  #               containerCommand: ''
  #               appSettings: ''
  #               configurationStrings: ''
